version: '3.1'

services:
  cassandra:
    image: cassandra
    ports:
      - '9042:9042'

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: microservice-app
    ports:
      - '3307:3306'

  elasticsearch:
    image: library/elasticsearch:6.8.23
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      discovery.type: single-node
